### PR TITLE
Add support for scram-sha-256 authentication

### PR DESCRIPTION
**Pull request by snsinfu**
This PR adds a support for scram-sha-256 authentication.

### CODE REVIEW

**Comment by snsinfu** [comment]
The checks seem to have failed due to a network error, but on my computer `docker-compose up` runs fine.

**Comment by Soremwar** [comment]
I tried it locally in my machine and it didn't work either. This is I suspect a problem on how the Docker testing structure is currently executed. I'm gonna try and fix this upstream to make the tests pass

**Comment by Soremwar** [comment]
I had to create a whole new container for scram authentication, since enabling scram would sadly disable authentication for both md5 and clear passwords

**Review by Soremwar — APPROVED** [review]
This is an incredible contribution @snsinfu
I have no further comments, though I will probably iterate over this in order to trim down some of the SHA utilities and replace them with the Deno builtin crypto that is likely to land in a couple weeks. Also I'd like to check if this works with SSL (I understand it's a slightly different protocol)

**Pull request merged**
