### PR TITLE
Allow `using` keyword with pool clients

### PR DESCRIPTION
**Pull request by langpavel**
Related to #472

- [x] PoolClient
- [x] test for `using client = await POOL.connect();`

### CODE REVIEW

**Comment by langpavel** [comment]
This PR can be merged independently

**Comment by langpavel** [comment]
Amended formating

**Comment by langpavel** [comment]
Amended linting, sorry :-)

**Comment by langpavel** [comment]
I fixed anothred deno lint error. Now everything should be green I hope

**Comment by bombillazo** [comment]
You can run `deno fmt --check` , `deno lint`, `deno test --doc client.ts mod.ts pool.ts client/ connection/ query/ utils/` from your project terminal if you want to anticipate what will fail.

**Comment by langpavel** [comment]
Pipeline failed on main branch on `deno fmt --check` :man_facepalming:

**Comment by bombillazo** [comment]
Please make a new PR to fix

**Pull request merged**
