### PR TITLE
feat: JSR support

### PR DESCRIPTION
**Pull request by iuioiua**
Done so `deno publish --dry-run` passes.

### CODE REVIEW

**Comment by bombillazo** [comment]
Hey, for my knowledge, Im new to deno, what is deno JSR?

**Comment by iuioiua** [comment]
JSR is a new package registry actively being developed by Deno. Take a look here: https://jsr.io/

**Comment by iuioiua** [comment]
PTAL @bartlomieju. I'll publish to JSR once merged.

**Review by bartlomieju — COMMENTED** [review]
@iuioiua can we do it on a separate branch so that current library can still be published to `deno.land/x/`?

**Comment by iuioiua** [comment]
Ok, I'll have to rework this to support both.

**Comment by iuioiua** [comment]
Closing in favour of #453.

**Pull request closed without merging**
