### PR TITLE
Upgrade to Deno 1.6.0

### PR DESCRIPTION
**Pull request by Soremwar**

### CODE REVIEW

**Comment by Soremwar** [comment]
@hayd Would you prefer the variables to be renamed to upper case or just lint ignore them?

**Comment by hayd** [comment]
Thanks @Soremwar! renaming is good.
I don't know if the Oid is case sensitive though?

**Comment by Soremwar** [comment]
Done @hayd
I renamed all variables to uppercase and opted for snake case in the oid

**Comment by Soremwar** [comment]
@hayd Can you give a quick review to this? 1.6.0 is really needed right now

**Pull request merged**
